const IN_CLAUSE_LIMIT = 999;
const MAX_MULTI_VALUES = 50000;
const QUERY_TIMEOUT_MS = 60000;
const EXPORT_STREAM_THRESHOLD = 50000;
const MAX_CONCURRENT_EXPORTS = 5;
const GTT_BATCH_SIZE = 5000;

module.exports = {
  IN_CLAUSE_LIMIT,
  MAX_MULTI_VALUES,
  QUERY_TIMEOUT_MS,
  EXPORT_STREAM_THRESHOLD,
  MAX_CONCURRENT_EXPORTS,
  GTT_BATCH_SIZE,
};
